import shell from 'shelljs';
export default function handler(req, res) {
  const { podName } = req.body;
  console.log(podName)
  let output = shell.exec(`kubectl describe node ${podName}`);
  console.log(output);
  // display the logs generated by the command above
  res.status(201).json({ success: true, logs: output })
}